version: '3.9'
services:
  db:
    image: postgres:alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=6201111
      - POSTGRES_DB=students_db

  app:
    build: .
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080" ]
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_URL=postgresql://postgres:6201111@db:5432/students_db
    volumes:
      - .:/app

volumes:
  postgres_data:
