"""third

Revision ID: 375dc131f788
Revises: 09c43bcca39e
Create Date: 2023-06-11 01:00:17.233120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375dc131f788'
down_revision = '09c43bcca39e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
