"""fix_1

Revision ID: 246bb6080482
Revises: 20a07895082b
Create Date: 2023-06-17 12:31:33.777336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246bb6080482'
down_revision = '20a07895082b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
